#include "graphics_api_gl_shaders.h"

const char* spritzGlQuadShaderVS =
    "#version 410 core\n"
    "layout (location = 0) in vec2 iPos;\n"
    "layout (location = 1) in int iTexIndex;\n"
    "layout (location = 2) in vec2 iTexCoords;\n"
    "layout (location = 3) in vec4 iColor;\n"
    "layout (location = 4) in float iTexAndColorBlendFactor;\n"
    "\n"
    "out vec4 color;\n"
    "\n"
    "flat out int texIndex;\n"
    "\n"
    "out vec2 texCoords;\n"
    "\n"
    "out float texAndColorBlendFactor;\n"
    "\n"
    "uniform mat4 uView;\n"
    "\n"
    "uniform mat4 uProj;\n"
    "\n"
    "void main() {\n"
    "    gl_Position = uProj * uView * vec4(iPos, 0.0, 1.0);\n"
    "    color = iColor;\n"
    "    texCoords = iTexCoords;\n"
    "    texIndex = iTexIndex;\n"
    "    texAndColorBlendFactor = iTexAndColorBlendFactor;\n"
    "}\n";

const char* spritzGlQuadShaderFS =
    "#version 410 core\n"
    "\n"
    "in vec4 color;\n"
    "\n"
    "flat in int texIndex;\n"
    "\n"
    "in vec2 texCoords;\n"
    "\n"
    "in float texAndColorBlendFactor;\n"
    "\n"
    "out vec4 oColor;\n"
    "\n"
    "uniform sampler2D samplers[16];\n"
    "\n"
    "void main() {\n"
    "    vec4 texColor = texture(samplers[texIndex], texCoords);\n"
    "    oColor = mix(texColor, color, 1 - texAndColorBlendFactor);\n"
    "    oColor.a = texColor.a == 0.0f ? 0.0f : color.a;"
    "}\n"
    ;
